customhost = "employee.ccuybctlirf7.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "cheahcherkiang-employee"
customregion = "us-east-1"
